### ISSUE TITLE
commit 513a959 can not run directly because luhhujbb/sigmund "0.2.1"

### ISSUE THREAD

**Issue by humorless** [humorless/cauchy#1]
commit 513a95919c01b079f7474277f9dbb72572c7c3e0 can not run directly because luhhujbb/sigmund "0.2.1"  cannot be download directly by leiningen. 

After certain modification, it can run. 
```
diff --git a/project.clj b/project.clj
index 682b2a6..9b440ef 100644
--- a/project.clj
+++ b/project.clj
@@ -25,8 +25,8 @@
                  [clj-http "2.1.0"]
                  [indigenous "0.1.0"]
                  [bultitude "0.2.8"]
-                 [luhhujbb/sigmund "0.2.1" :exclusions [log4j sigar/sigar-native-deps]]
+                 [sigmund "0.1.1" :exclusions [log4j sigar/sigar-native-deps]]
                  [clj-sockets "0.1.0"]
                  [stask/sigar-native-deps "1.6.4"]]
-  :aot :all
+  ;:aot :all
   :main cauchy.core)
```

Invoke command is 
```
lein run ./conf/cauchy.edn,./conf/profiles/base.edn
```

**Comment by humorless** [comment]
**Update**

After start, there is still problems:
```
1    [main] INFO  cauchy.core  - loading ./conf/cauchy.edn
4    [main] INFO  cauchy.core  - loading ./conf/profiles/base.edn
227  [main] INFO  indigenous.core  - Lib was already there: /tmp/sigar/libsigar.so
374  [main] INFO  cauchy.core  - Cauchy Service start with jobs {alive {:interval 12, :active true, :job-fn #object[user$eval11724$fn__11725 0x14d43f13 us
er$eval11724$fn__11725@14d43f13]}, load {:interval 20, :job-ns cauchy.jobs.health, :job-fn load-average}, memory {:interval 20, :job-ns cauchy.jobs.health
, :job-fn memory}, swap {:interval 20, :job-ns cauchy.jobs.health, :job-fn swap}, disk {:interval 20, :job-ns cauchy.jobs.health, :job-fn disk}, disk_io {
:interval 20, :job-ns cauchy.jobs.health, :job-fn disk-io}, net_bandwidth {:interval 20, :job-ns cauchy.jobs.health, :job-fn bandwidth}}
375  [main] INFO  cauchy.core  - Scheduling job {:interval 12, :active true, :job-fn #object[user$eval11724$fn__11725 0x14d43f13 user$eval11724$fn__11725@
14d43f13]}
384  [main] INFO  cauchy.scheduler  - added job alive
384  [main] INFO  cauchy.core  - Scheduling job {:interval 20, :job-ns cauchy.jobs.health, :job-fn load-average}
582  [main] INFO  cauchy.scheduler  - added job load
582  [main] INFO  cauchy.core  - Scheduling job {:interval 20, :job-ns cauchy.jobs.health, :job-fn memory}
616  [main] INFO  cauchy.scheduler  - added job memory
616  [main] INFO  cauchy.core  - Scheduling job {:interval 20, :job-ns cauchy.jobs.health, :job-fn swap}
655  [main] INFO  cauchy.scheduler  - added job swap
655  [main] INFO  cauchy.core  - Scheduling job {:interval 20, :job-ns cauchy.jobs.health, :job-fn disk}
692  [main] INFO  cauchy.scheduler  - added job disk
692  [main] INFO  cauchy.core  - Scheduling job {:interval 20, :job-ns cauchy.jobs.health, :job-fn disk-io}
731  [main] INFO  cauchy.scheduler  - added job disk_io
731  [main] INFO  cauchy.core  - Scheduling job {:interval 20, :job-ns cauchy.jobs.health, :job-fn bandwidth}
764  [main] INFO  cauchy.scheduler  - added job net_bandwidth
764  [main] INFO  cauchy.core  - Cauchy successfully started
Exception in thread "async-thread-macro-1" java.lang.NoSuchMethodError: com.google.protobuf.LazyStringList.getUnmodifiableView()Lcom/google/protobuf/LazyS
tringList;
        at io.riemann.riemann.Proto$Event$Builder.buildPartial(Proto.java:2359)
        at io.riemann.riemann.Proto$Event$Builder.build(Proto.java:2327)
        at riemann.codec$encode_pb_event.invoke(codec.clj:80)
        at riemann.codec$encode_client_pb_event.invoke(codec.clj:87)
        at riemann.client$send_event.invoke(client.clj:71)
        at cauchy.output.riemann$send_BANG_.invoke(riemann.clj:20)
        at clojure.core$map$fn__4553.invoke(core.clj:2622)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:507)
        at clojure.core$seq__4128.invoke(core.clj:137)
        at clojure.core$dorun.invoke(core.clj:3009)
        at clojure.core$doall.invoke(core.clj:3025)
        at cauchy.core$start_BANG_$fn__11703$job_fn__11706.invoke(core.clj:131)
        at cauchy.scheduler$do_schedule$fn__11396.invoke(scheduler.clj:49)
        at chime$chime_at$fn__11339$state_machine__9308__auto____11340$fn__11342$inst_11326__11348.invoke(chime.clj:69)
        at clojure.core.async$thread_call$fn__9496.invoke(async.clj:434)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by humorless** [comment]
Adding an explicit dependency on protobuf-java fixes the issue.
```
 [com.google.protobuf/protobuf-java  "3.1.0"]
```

**Comment by luhhujbb** [comment]
I've released my sigmund version into clojars last week. I will fix protobuf deps tomorrow, However I will prefer protobuf version 2.6.1 which is directly supported by ubuntu LTS 16.04.
